dist: bionic
#language: r
before_install:
- sudo apt-get -qq update && sudo apt-get install -qq -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended latex-beamer texlive-science
#- tlmgr install index
#- sudo tlmgr init-usertree
#- tlmgr install --reinstall --repository https://www.komascript.de/repository/texlive/2020 koma-script\
install: skip
script:
- bash .ci/travis/make_all.sh
after_success:
- bash .ci/travis/zip_pdfs.sh
deploy:
  provider: releases
  token: "$GITHU8_API_KEY"
  file_glob: true
  file:
  - "./notes/**/tutorial_*.slides.pdf"
  - "./notes/**/tutorial_*.notes.pdf"
  - "./tutorial_*.zip"
  skip_cleanup: true
  on:
    branch: master
#  edge: true

